apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    name: postgres-pod
    app: demo-voting-app
env:
  - name: POSTGRES_PASSWORD
    value: admin123

spec:
  containers:
    - name: postgres
      image: postgres
      ports:
        - containerPort: 5432